site_name: My Docs
theme:
  features:
    - content.action.edit
    - content.action.view
  icon:
    repo: simple/github
    edit: material/pencil 
    view: material/eye
    
  palette:
    scheme: slate
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

repo_url: https://github.com/squidfunk/mkdocs-material

plugins:
  - search
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  
copyright: |
  &copy; 2023 <a href="https://e-z.bio/tinnyterr"  target="_blank" rel="noopener">TinnyTerr</a>
