site_name: My Docs
theme:
  icon:
    repo: simple/github
    edit: material/pencil 
    view: material/eye
    
  palette:
    scheme: slate
    accent: indigo
    primary: deep orange

  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.highlight
    - content.code.copy
  language: en

repo_url: https://github.com/tinnyterr/tinnyterr.github.io



plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - search
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  
copyright: |
  &copy; 2023 <a href="https://e-z.bio/tinnyterr"  target="_blank" rel="noopener">TinnyTerr</a>
